name: AcuteLoot
version: ${project.version}
main: acute.loot.AcuteLoot
api-version: 1.13
softdepend:
  - "ProtocolLib"
authors: ["zizmax", "dizigma"]
description: Custom loot names and effects in Minecraft
commands:
  acuteloot:
    description: AcuteLoot parent command
    usage: /<command> [add|remove|reload|stats|help|new]
    aliases: [al]
permissions:
  acuteloot.*:
    description: All AcuteLoot permissions
    default: op
  acuteloot:
    default: op
  acuteloot.help:
    default: true
  acuteloot.enchant:
    description: To be able to create AcuteLoot items in enchanting table
    default: true
  acuteloot.new:
    default: op
  acuteloot.reload:
    default: op
  acuteloot.add:
    default: op
  acuteloot.remove:
    default: op
  acuteloot.rename:
    default: op
  acuteloot.stats:
    default: op
  acuteloot.name:
    default: op
  acuteloot.salvage:
    default: op
  acuteloot.salvage-force-open:
    default: op
  acuteloot.give:
    default: op
  acuteloot.reroll:
    default: true
  acuteloot.rmchest:
    default: op
  acuteloot.share:
    default: op
  acuteloot.repair:
    default: op
  acuteloot.enable:
    default: op
  acuteloot.disable:
    default: op
